### ISSUE TITLE
Optoisolator is unnecessary

### ISSUE THREAD

**Issue by jaseg** [xoseperez/espurna-board#1]
As the design is non-isolated anyway and also the relay already provides a fair amount of isolation *and* is powered from the same rail anyway, the optoisolator is completely redundant.

**Comment by krisnadn11** [comment]
Can you explain in more detail about this? 

Because relays sold in the market generally use an Optocoupler circuit (PC-817C). As far as I know, this semiconductor is used to provide good galvanic isolation between the control section and the power section of the relay. This galvanic isolation helps protect the control circuit from high voltages or currents that may be present on the power circuit.

**Comment by jaseg** [comment]
Note that this issue is more than six years old, and the current design does not include an optoisolator anymore.

In the old version of the design that this issue refers to, the microcontroller part was grounded to one of the mains inputs. The author probably copied the optoisolator from a schematic of a relay module somewhere, but in this circuit, there was no galvanic isolation between the microcontroller and the mains input either way, with or without the optoisolator, so all it did was use a lot of board space and unnecessarily consume current.

Note that a relay already provides good galvanic protection between its coil and its contacts. The optoisolator the cheap relay boards use isolates the control inputs from the coils (not the output), but that is only a concern in the first place when you have separate power supplies for the relay coils and for the microcontroller. To deal with inductive voltage spikes from the relays, you use a freewheeling diode, which is present in both versions of this design. If you power the relay coils and the microcontroller from one power supply (or from two that share the same ground), you can just use a mosfet straight and mind the relay coil's ground connections. I think this is just an instance of people cargo-culting on a design decision that was sensible at some point for some use cases, but usually is unnecessarily complicated.
